---
author: "Samantha Rubo"
date: "2023-04-20"
output:
  pdf_document: 
    extra_dependencies: ["float"]
    keep_tex: true
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
lang: de
params:
  betrieb: Haas
  feld: Rosengarten
  satz: 1
  filepath_tf: ../../data/derived_data/Model2/ANNI_Tensorflow_20230420
  scaling_data_path: ../../data/derived_data/Model2/scaling_data.csv
  wetter_anbau_daten_csv: ../../data/derived_data/Wetterdaten_Praxis/Rosengarten_id_Worms/daten_komplett.csv
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = FALSE, fig.pos = "H", out.extra = "", 
                      message = FALSE, warning = FALSE)
#fig.pos = "H", out.extra = "" geben an, dass Position der Grafiken genau an der Stelle
#unter dem Chunk erscheint, und Latex sie nicht selbst plaziert
```

---
title: "ANNI Paxisphase 2023: Fa. `r params$betrieb`, Feld `r params$feld`" 
---


```{r}
library(keras)
library(mlbench)
library(dplyr)
library(ggplot2)
#library(data.table)
library(cowplot)
```

<!-- ## Vorgehen: -->

<!-- 1\. Gespiechertes Modell laden -->

```{r, eval=TRUE}
filepath_tf <- params$filepath_tf
#"../../data/derived_data/Model2/ANNI_Tensorflow_20230420"
new_model <- load_model_tf(filepath_tf)
```

<!-- 2\. Skalierungs-Werte für Input-Daten laden -->

```{r}
scaling_data <- data.table::fread(params$scaling_data_path)
```

<!-- 3\. Wetter- und Anbaudaten einlesen -->

```{r}
satz_raw <- data.table::fread(params$wetter_anbau_daten_csv)
satz_scaled <- scale(satz_raw, center = scaling_data$m, scale = scaling_data$s)
```

<!-- 4\. ANNI für jeden Tag einzeln hintereinander im Loop ausführen -->

```{r}
predictions_anni <- matrix(ncol = 6, nrow = nrow(satz_scaled))

for (i in 1:(nrow(satz_scaled)-1)){
    
    predictions_anni[i,] <- new_model %>%
        predict(x = matrix(nrow = 1, satz_scaled[i,]), verbose = 0)
    satz_scaled[i+1,1:6] <- scale(matrix(predictions_anni[i,], nrow = 1),
                                  center = scaling_data$m[1:6],
                                  scale = scaling_data$s[1:6])
    k_clear_session()
}

```

<!-- 5\. Ergebnisse formatieren -->

```{r}
y2 <- predictions_anni[-NROW(predictions_anni),] %>% as.data.frame() %>%
    mutate(tage_seit_aussaat = satz_raw$tage_seit_aussaat[-1]) %>%
    tidyr::pivot_longer(cols = -tage_seit_aussaat,
                        values_to = "predicted_nFK",  names_to = "depth")

result <- y2 %>%
    mutate_at("depth",
              ~factor(., labels = c("nFK_0010", "nFK_1020", "nFK_2030",
                                    "nFK_3040", "nFK_4050", "nFK_5060") )) %>%
    mutate_at("predicted_nFK", ~round(., 2))
```

```{r}
cap <- paste0("Ergebnis des Bewässerungsmodells ANNI für die Fläche \\textit{", params$feld,  "} der Fa. ",  params$betrieb, " für die Tage ", paste0(range(satz_raw$tage_seit_aussaat), collapse = "-"), " seit Aussaat. Dargestellt sind A) Wetterdaten für Niederschlag (mm) und mittlerer Tagestemperatur (°C) und B) die modellierte nutzbare Feldkapazität (nFK \\%) für 6 Bodentiefen von 0-60 cm Tiefe.")
```

<!-- 6\. ANNI-Ergebnis plotten -->

\

```{r, fig.width=7, fig.height=5, warning=FALSE, fig.cap=cap}
#Regen plotten:
p2 <- ggplot(satz_raw, aes(x = tage_seit_aussaat)) +
    geom_col(aes(x = tage_seit_aussaat-1, y = wasser_input_Vortag,
                 fill = "Niederschlag")) +
    geom_line(aes(y = Tmean_gradC/1.3, col = "Temperatur")) +
    theme_bw() +
    theme(panel.grid = element_blank(),
          plot.margin = margin(t=20, r = 10, b = 0, l = 30, "points"),
          axis.title.y.right = element_text(margin = margin(l = 10, "pt")),
          legend.title = element_text(margin = margin(b = 10, unit = "pt")),
          legend.margin = margin(b = 0, t = -30, unit = "pt")) +
    ylab("Niederschlag (mm)") + xlab(NULL) +
    scale_y_continuous(expand = expansion(add = c(0,10)),
                       sec.axis =
                           sec_axis(~.*1.3,
                                    name = "Tagesmittel-\nTemperatur (°C)")) +
    scale_x_continuous(expand = expansion(add = c(0,0)),
                       limits = c(range(satz_raw$tage_seit_aussaat))) +
    scale_fill_manual("Wetterdaten", values = c("Niederschlag" = "grey40")) +
    scale_color_manual("", values = c("Temperatur" = "grey20")) +
    guides(fill = guide_legend(order = 1), color = guide_legend(order = 2))

#ANNI plotten:
p1 <- ggplot(result) +
    geom_area(data = data.frame(x = c(range(satz_raw$tage_seit_aussaat)),
                                y = 60,
                                fill = "Bewässerungs-\nSchwellenwert"),
              aes(x=x, y=y, fill=fill))+
    geom_ribbon(data = data.frame(x=c(range(satz_raw$tage_seit_aussaat)),
                                  ymin = 100,
                                  ymax = Inf,
                                  fill = "Auswaschung"),
                aes(x=x, ymin=ymin, ymax=ymax, fill=fill)) +
    geom_line(aes(tage_seit_aussaat, predicted_nFK, col = depth)) +
    ylab("nFK (%)") + xlab("Tage seit Aussaat") +
    theme_bw() +
    theme(panel.grid = element_blank(), legend.position = "right") +
    scale_y_continuous(expand = expansion(add = c(0,10)),
                       breaks = seq(0,100, by = 20)) +
    scale_x_continuous(expand = expansion(add = c(0,0))) +
    scale_x_continuous(expand = expansion(add = c(0,0)),
                       limits = c(range(satz_raw$tage_seit_aussaat))) +
    scale_fill_manual("", values = c("Bewässerungs-\nSchwellenwert" = "grey90",
                                     "Auswaschung" = "lightblue")) +
    scale_color_discrete("Bodentiefe nFK")



#Beide Plots zusannefügen:
p3 <- plot_grid(p2, p1, labels = c('A', 'B'), label_size = 12, ncol = 1,
                align = "hv", rel_heights = c(1,2), axis="t")
p3
```

```{r}
### Grafik speichern
pfad0 <- "../../graphics/ANNI_Praxis/"
feldinfo <- paste(params$betrieb, params$feld, "Satz", params$satz,
                  sep = "_")
zeitraum <- paste0("_DAS", paste0(range(satz_raw$tage_seit_aussaat),
                                  collapse = "_"))
#zeitstempel <- Sys.Date() %>% format("%Y%m%d")
full_name <- paste0(pfad0, paste0(feldinfo, zeitraum, collapse = "_"))

ggsave(p3, filename = paste0(full_name, ".png"), device = "png",
       width = 7, height = 5)

options(width = 80)
foot1 <- (paste0("ANNI Grafik gespeichert unter:\n", file.path(paste0(full_name, ".png"))))
```

```{r}
#Output-Daten speichern:
pfad_csv <- "../../data/derived_data/ANNI_Praxis/"
full_name_csv <- paste0(pfad_csv, paste0(feldinfo, zeitraum, collapse = "_"))
data.table::fwrite(x = result, file = paste0(full_name_csv, ".csv"))

foot2 <- (paste0("ANNI CSV gespeichert unter:\n", file.path(paste0(full_name_csv, ".csv"))))
```

Anmerkung: ANNI wurde in einer Schleife ausgeführt, so dass die modellierte nFK (Output n) als Input (n+1) des folgenden Tages eingeht. [^1] [^2]

[^1]: `r foot1`

[^2]: `r foot2`
