---
#author: "Samantha Rubo"
#date: "2023-04-20"
output:
  pdf_document: 
    extra_dependencies: ["float"]
    keep_tex: true
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
lang: de
params:
  betrieb: Haas
  feld: Kämmerwiese
  satz: 1
  # filepath_tf: ../../data/derived_data/Model2/ANNI_Tensorflow_20230420
  # scaling_data_path: ../../data/derived_data/Model2/scaling_data.csv
  filepath_tf1: ../../data/derived_data/Model5_DWD_pretrained/ANNI_Tensorflow_Schicht0010cm_20230824
  filepath_tf2: ../../data/derived_data/Model5_DWD_pretrained/ANNI_Tensorflow_Schicht2030cm_20230824
  filepath_tf3: ../../data/derived_data/Model5_DWD_pretrained/ANNI_Tensorflow_Schicht5060cm_20230824
  scaling_data_path: ../../data/derived_data/scaling_data_alle_Daten_DWD_20230824.csv
  wetter_anbau_daten_csv: ../../data/derived_data/Wetterdaten_Praxis/Mittelgewann/daten_komplett.csv
  bewaesserungs_csv: ../../data/derived_data/Wetterdaten_Praxis/Mittelgewann/bewaesserung.csv
  datum_aussaat: "2023-08-23"
  start_nFK: !r c(100, 100, 100, 100, 100, 100)
  #start_nFK: !r c(87.7, 87.0, 62.1, 35.8, 25.3, 33.9)
---


```{r, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = FALSE, fig.pos = "H", out.extra = "", 
                      message = FALSE, warning = FALSE)
#fig.pos = "H", out.extra = "" geben an, dass Position der Grafiken genau an der Stelle
#unter dem Chunk erscheint, und Latex sie nicht selbst plaziert
```

---
title: "ANNI Paxisphase 2023: Fa. `r params$betrieb`, Feld `r params$feld`" 
---

```{r, message=FALSE}
library(keras)
library(mlbench)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(data.table)
library(cowplot)
library(lubridate)
library(tidyr)
```

Aussaat-Datum: `r format.Date(as_date(params$datum_aussaat), "%d.%m.%Y")`

<!-- ## Vorgehen: -->

<!-- 1\. Gespiechertes Modell laden -->

```{r, eval=TRUE}
# filepath_tf <- params$filepath_tf
# new_model <- load_model_tf(filepath_tf)

filepath_tf1 <- params$filepath_tf1
filepath_tf2 <- params$filepath_tf2
filepath_tf3 <- params$filepath_tf3

new_model1 <- load_model_tf(filepath_tf1)
new_model2 <- load_model_tf(filepath_tf2)
new_model3 <- load_model_tf(filepath_tf3)
```

<!-- 2\. Skalierungs-Werte für Input-Daten laden -->

```{r}
scaling_data <- data.table::fread(params$scaling_data_path)
```

<!-- 3\. Wetter- und Anbaudaten einlesen -->

```{r}
satz_raw <- data.table::fread(params$wetter_anbau_daten_csv)

satz_raw <- satz_raw %>%
    mutate(niederschlag_mm_sum = c(0,diff(niederschlag_mm_sum))) 

#Skalierung: nur notwendige Daten filtern:
names1 <- names(satz_raw)
scaling_data <- scaling_data[match(names1,scaling_data$parameter),]
#bei original-ANNI: scaling_data nicht ändern!



#Anbau-Daten skalieren:
satz_scaled <- scale(satz_raw, center = scaling_data$m, scale = scaling_data$s)

#Anwender-Schätzung der nFK anfügen:
nfk_anwender <- fread(paste0(dirname(params$wetter_anbau_daten_csv), "/nFK_schaetzung_anwender.csv"))
nfk_anwender_scaled <- scale(nfk_anwender[,-1], center = scaling_data$m[1:6], scale = scaling_data$s[1:6])
```

<!-- ## Genutzte Parameter der 3 Modelle -->

```{r}
#nFK_0010
used1 <- c("Tmean_gradC", "Tmin_gradC", "Tmax_gradC", "relLuftfeuchte_mean_prozent", "relLuftfeuchte_min_prozent", "globalstrahlung_Wh_m2", "windgeschwindigkeit_m_s", "niederschlag_mm_sum", "wasser_input_Vortag", "nFK_0010_Vortag", "nFK_2030_Vortag", "tage_seit_aussaat", "Tmean_th9_25_gradC", "ibi", "irmi")

#"nFK_2030"
used2 <- c("Tmean_gradC", "Tmin_gradC", "Tmax_gradC", "relLuftfeuchte_mean_prozent", "globalstrahlung_Wh_m2", "niederschlag_mm_sum", "wasser_input_Vortag", "nFK_0010_Vortag", "nFK_2030_Vortag", "nFK_5060_Vortag", "tage_seit_aussaat", "Tmean_th9_25_gradC", "ibi", "irmi", "Tmean_gradC_sum", "Tmean_th9_25_gradC_sum", "globalstrahlung_Wh_m2_sum", "tageslicht_h_sum", "tageslicht_h_th9_sum")

#"nFK_5060"
used3 <- c("Tmean_gradC", "globalstrahlung_Wh_m2", "niederschlag_mm_sum", "wasser_input_Vortag", "nFK_0010_Vortag", "nFK_2030_Vortag", "nFK_5060_Vortag", "tage_seit_aussaat", "ibi", "irmi", "Tmean_gradC_sum", "tageslicht_h_sum", "tageslicht_h_th9_sum")
```


<!-- 4\. ANNI für jeden Tag einzeln hintereinander im Loop ausführen -->
```{r}
# Original_ Ein Modell mit 6 Ausgabewerten (nFK in 6 Schichten)
# predictions_anni <- matrix(ncol = 6, nrow = nrow(satz_scaled))
# 
# for (i in 1:(nrow(satz_scaled)-1)){
# 
#     predictions_anni[i,] <- new_model %>%
#         predict(x = matrix(nrow = 1, satz_scaled[i,]), verbose = 0)
#     satz_scaled[i+1,1:6] <- scale(matrix(predictions_anni[i,], nrow = 1),
#                                   center = scaling_data$m[1:6],
#                                   scale = scaling_data$s[1:6])
#     k_clear_session()
# 
# anwender_nfk_i <- unlist(nfk_anwender_scaled[i+1,])
#     anwender_nfk_i_raw <- unlist(nfk_anwender[i+1,-1])
#     if(all(!is.na(anwender_nfk_i))) {
#         satz_scaled[i+1,1:6] <- anwender_nfk_i[1:6];
#         predictions_anni[i,1:6] <- anwender_nfk_i_raw[1:6];
#     }
# 
# 
# }

```

<!-- # 3 Einzel-Modelle für 3 Bodenschichten laufen lassen: -->
```{r}
predictions_anni1 <- matrix(ncol = 1, nrow = nrow(satz_scaled)-1)
predictions_anni2 <- matrix(ncol = 1, nrow = nrow(satz_scaled)-1)
predictions_anni3 <- matrix(ncol = 1, nrow = nrow(satz_scaled)-1)

for (i in 1:(nrow(satz_scaled)-1)){
    
    #nFK_0010_Vortag
    predictions_anni1[i,] <- new_model1 %>%
        predict(x = matrix(nrow = 1, satz_scaled[i,used1]), verbose = 0)
    satz_scaled[i+1,1] <- scale(matrix(predictions_anni1[i,], nrow = 1), 
                                center = scaling_data$m[1], 
                                scale = scaling_data$s[1]) 
    
    #nFK_2030_Vortag
    predictions_anni2[i,] <- new_model2 %>%
        predict(x = matrix(nrow = 1, satz_scaled[i,used2]), verbose = 0)
    satz_scaled[i+1,3] <- scale(matrix(predictions_anni2[i,], nrow = 1), 
                                center = scaling_data$m[3], 
                                scale = scaling_data$s[3]) 
    #nFK_5060_Vortag
    predictions_anni3[i,] <- new_model3 %>%
        predict(x = matrix(nrow = 1, satz_scaled[i,used3]), verbose = 0)
    satz_scaled[i+1,6] <- scale(matrix(predictions_anni3[i,], nrow = 1), 
                                center = scaling_data$m[6], 
                                scale = scaling_data$s[6]) 
    k_clear_session()
    
    #i=19
    anwender_nfk_i <- unlist(nfk_anwender_scaled[i+1,])
    anwender_nfk_i_raw <- unlist(nfk_anwender[i+1,-1])
    if(all(!is.na(anwender_nfk_i))) {
        satz_scaled[i+1,c(1,3,6)] <- anwender_nfk_i[c(1,3,6)];
        predictions_anni1[i,] <- anwender_nfk_i_raw[1];
        predictions_anni2[i,] <- anwender_nfk_i_raw[3];
        predictions_anni3[i,] <- anwender_nfk_i_raw[6]
    }
    
}

```



<!-- #ANNI-Output zusammentragen und interpolieren: -->
```{r}
#bei Original-ANNI:
#all_nFK_out <- predictions_anni %>% as_tibble %>% slice(-n())
    
all_nFK_out <- data.frame(
    nFK_0010 = predictions_anni1, 
    nFK_1020 = NA,
    nFK_2030 = predictions_anni2, 
    nFK_3040 = NA,
    nFK_4050 = NA,
    nFK_5060 = predictions_anni3) %>%
    #interpolation:
    t %>% as.data.frame() %>%
    mutate(across(everything(), ~approx(., n=6)$y)) %>%
    t %>% as.data.frame()
```


<!-- 5\. Ergebnisse formatieren -->

```{r}
y2 <-all_nFK_out %>%
    #predictions_anni[-NROW(predictions_anni),] %>% as.data.frame() %>%
    mutate(tage_seit_aussaat = satz_raw$tage_seit_aussaat[-1]) %>%
    tidyr::pivot_longer(cols = -tage_seit_aussaat,
                        values_to = "predicted_nFK",  names_to = "depth")

result <- #100% nFK für Tag 1 anfügen:
    bind_rows(data.frame(tage_seit_aussaat =  1,
                         depth = unique(y2$depth),
                         #predicted_nFK = 100), ## Startwerte anpassen!
                         predicted_nFK = params$start_nFK), ## Startwerte anpassen!
              
              y2) %>%
    mutate_at("depth",
              ~factor(., labels = c("nFK_0010", "nFK_1020", "nFK_2030",
                                    "nFK_3040", "nFK_4050", "nFK_5060") )) %>%
    mutate_at("predicted_nFK", ~round(., 2))
```

<!-- # 5.1 nFK der durchwurzelten Bodenschicht berechnen: -->
```{r}
wurzel_df <- fread(paste0(dirname(params$wetter_anbau_daten_csv), "/durchwurzelte_schicht.csv"))
ann_durchwurzelte_schicht <- result %>% 
    mutate(schicht = substr(depth, 7,8)) %>%
    left_join(wurzel_df, by = "tage_seit_aussaat") %>%
    filter(schicht <= durchwurzelte_schicht_10cm) %>%
    group_by(tage_seit_aussaat) %>%
    summarise(nFK_anni = mean(predicted_nFK), .groups = "drop")
```

<!-- ## Bewässerungs-Termin berechnen und als als Text ausgeben -->
```{r}
zeitpunkt_bewaessern_in_prognose <- tail(ann_durchwurzelte_schicht, n = 5) %>% 
    filter(nFK_anni < 60) %>% slice(1) %>% pull(tage_seit_aussaat)

#Falls die Bewässerung in der Vergangenheit:  auf heute verschieben
if(length(zeitpunkt_bewaessern_in_prognose) != 0){
    datum_bewaessern <- as_date(params$datum_aussaat) + zeitpunkt_bewaessern_in_prognose
    morgen <- as.numeric(Sys.Date() - as_date(params$datum_aussaat) + 0)
    if(datum_bewaessern <= Sys.Date()) {zeitpunkt_bewaessern_in_prognose <- morgen}
}

#Fallse es genug regnet in der Prognose: dann Bewässerung rückstellen:
niederschlag_prognose <- tail(satz_raw$niederschlag_mm_sum, n = 4) 
regen_statt_bewaessern <- sum(niederschlag_prognose) > 25 | any(niederschlag_prognose >= 15)

if(regen_statt_bewaessern) {zeitpunkt_bewaessern_in_prognose <- zeitpunkt_bewaessern_in_prognose[-1]}

date1 <- lubridate::as_date(params$datum_aussaat)
wochentag <- c("Mo", "Di", "Mi", "Do", "Fr", "Sa", "So")
termin <- date1+zeitpunkt_bewaessern_in_prognose
wochentag_termin <- wochentag[as.numeric(format.Date(termin, "%u"))]

#"Nächste Bewässerung notwendig:" 
date_info <- paste0(wochentag_termin, ", ", format.Date(termin, "%d.%m.%y"))
bewaessern_text <- paste("in", (date1 + zeitpunkt_bewaessern_in_prognose)-Sys.Date(), "Tagen, am", date_info)

if (length(zeitpunkt_bewaessern_in_prognose) == 0) {
    bewaessern_text <- "Keine Bewässerung in den 3 nächsten Tagen notwendig."}
```

Bewässerungs-Prognose: `r bewaessern_text`

```{r}
# Für Plot: falls keine Termin (leerte zeipuntk_...): fiktiv auf 100 setzen, um außerhalb des Plot
if (length(zeitpunkt_bewaessern_in_prognose) == 0) {zeitpunkt_bewaessern_in_prognose <- 100}
```



```{r}
cap <- paste0("Ergebnis des Bewässerungsmodells ANNI für die Fläche \\textit{", params$feld,  "} der Fa. ",  params$betrieb, " für die Tage ", paste0(range(satz_raw$tage_seit_aussaat), collapse = "-"), " seit Aussaat. Dargestellt sind A) Wetterdaten für Niederschlag (mm) und Tageshöchsttemperatur (°C) und B) die modellierte nutzbare Feldkapazität (nFK \\%) für 6 Bodentiefen von 0-60 cm Tiefe.")
```

<!-- 6\. ANNI-Ergebnis plotten -->
\
```{r, warning=F}
#Datums-Achse (2. X-Achse oben) anpassen:
v_heute <- as.numeric(Sys.Date() - date1)
prognose_ticks <- v_heute : max(satz_raw$tage_seit_aussaat)
date_seq1 <- seq.Date(date1, Sys.Date(), by = 1) 
pretty1 <- pretty(date_seq1)
pretty1 <- pretty1[pretty1 %in% date_seq1]
idx1 <- match(pretty1, date_seq1) -1 
idx2 <- c(idx1, prognose_ticks)
pretty2 <- c(as.character(format.Date(pretty1, "%d.%m")), rep(" ", times = length(prognose_ticks)))
v_label <- paste("heute:", format.Date(Sys.Date(), ("%d.%m.%y")))
```


<!-- #Bewässerung hinzufügen: -->
```{r}
bewaesserung_df <- fread(params$bewaesserungs_csv)
bewaesserung_df <- bewaesserung_df %>% 
    mutate(across(datum_bewaesserung, ~as_date(., format = "%d.%m.%y"))) %>%
     #mutate(across(datum_bewaesserung,~.+1)) %>%
    select(datum_bewaesserung, bewaesserungs_menge_mm) %>% drop_na()

wasser_df <- 
    satz_raw %>%
    select(tage_seit_aussaat, wasser_input_Vortag) %>% 
    mutate(datum = as_date(params$datum_aussaat) + tage_seit_aussaat -2) %>%
    left_join(bewaesserung_df, by = c("datum" = "datum_bewaesserung")) %>%
    mutate(across(bewaesserungs_menge_mm, ~ifelse(is.na(.),0,.))) %>%
    mutate(across(wasser_input_Vortag, ~.-bewaesserungs_menge_mm)) %>%
    mutate(across(wasser_input_Vortag, ~ifelse(.<0,0,.))) %>% 
    select(-datum) %>%
    pivot_longer(cols = -tage_seit_aussaat)
```

```{r, warning=F}
#Regen plotten:
korrekturfaktor <- 1.0
p2 <- ggplot(satz_raw, aes(x = tage_seit_aussaat)) +
    # geom_col(aes(x = tage_seit_aussaat-2, y = wasser_input_Vortag,
    #              fill = "Niederschlag")) +
    geom_col(data = wasser_df, aes(x = tage_seit_aussaat-2, y = value,
                                   fill = name)) +
    geom_line(aes(x = tage_seit_aussaat-1, y = Tmax_gradC /korrekturfaktor, col = "Temperatur")) + 
    theme_bw() +
    theme(panel.grid = element_blank(),
          plot.margin = margin(t=20, r = 10, b = 0, l = 30, "points"),
          axis.title.y.right = element_text(margin = margin(l = 10, "pt")),
          legend.title = element_text(margin = margin(b = 10, unit = "pt")),
          legend.margin = margin(b = 0, t = -30, unit = "pt")) +
    ylab("Niederschlag (mm)") + xlab(NULL) +
    scale_y_continuous(expand = expansion(add = c(0,5)),
                       sec.axis =
                           sec_axis(~.*korrekturfaktor,
                                    name = "Tageshöchst-\nTemperatur (°C)")) +
    scale_x_continuous(expand = expansion(add = c(0,0)),
                       limits = c(range(satz_raw$tage_seit_aussaat)), 
                       sec.axis = sec_axis(trans = ~.*1, breaks = idx2, 
                                           name = "Datum",
                                           labels = pretty2)) +
    
    
    #scale_fill_manual("Wetterdaten", values = c("Niederschlag" = "grey40")) +
    scale_fill_manual("Wetterdaten", 
                      values = c("wasser_input_Vortag" = "grey40",
                                 "bewaesserungs_menge_mm" = "grey70"), 
                      labels = c("wasser_input_Vortag"="Niederschlag",
                                 "bewaesserungs_menge_mm" = "Bewässerung")) +
    scale_color_manual("", values = c("Temperatur" = "grey20"), 
                       labels = c("Temperatur" = "Tageshöchstemperatur")) +
    guides(fill = guide_legend(order = 1), color = guide_legend(order = 2)) + 
    geom_vline(xintercept = v_heute, col = "blue")
#p2
#plotly::ggplotly(p2)
```

```{r, rows.print = 15}
# satz_raw %>% select(tage_seit_aussaat, wasser_input_Vortag, Tmax_gradC) %>%
#     mutate(datum_wasser = date1 + tage_seit_aussaat - 2, .before = "wasser_input_Vortag") %>%
#     mutate(datum_temp = date1 + tage_seit_aussaat -1 , .before = "Tmax_gradC")
```



```{r, warning=FALSE}
#ANNI plotten:

p1 <- ggplot(result) +
    geom_area(data = data.frame(x = c(range(satz_raw$tage_seit_aussaat)),
                                y = 60,
                                fill = "Bewässerungs-\nSchwellenwert"),
              aes(x=x, y=y, fill=fill))+
    geom_ribbon(data = data.frame(x=c(range(satz_raw$tage_seit_aussaat)),
                                  ymin = 100,
                                  ymax = Inf,
                                  fill = "Auswaschung"),
                aes(x=x, ymin=ymin, ymax=ymax, fill=fill)) +
    geom_line(aes(tage_seit_aussaat, predicted_nFK, col = depth)) +
    geom_line(data = ann_durchwurzelte_schicht,
              aes(tage_seit_aussaat, nFK_anni, 
                  col = "nFK durchwurzelter Boden"), linewidth = 1.5) +
    
    scale_color_manual("Bodentiefe nFK",
                       breaks = c(levels(result$depth), "nFK durchwurzelter Boden"),
                       #limits = c(levels(result$depth), "nFK durchwurzelter Boden"),
                       labels = c(levels(result$depth), "mittlere nFK des \ndurchwurzelten Bodens"),
                       values = c(scales::hue_pal()(6), "black" ) )+
    
    new_scale_colour() + 
    geom_point(aes(x=zeitpunkt_bewaessern_in_prognose, y= 5, col = "bewässern"), shape = 8, size = 6) + 
    scale_color_manual("",values = c("bewässern" = "deepskyblue2",
                                     "Schätzung Praxis" = "black")) + 
    
    #new_scale_colour() +
    
    # if(!is.na(any(nfk_anwender$nFK_0010))){
    # geom_point(data = nfk_anwender, aes(tage_seit_aussaat, as.factor(nFK_0010), 
    #                                     col = "Schätzung Praxis"), 
    #            size = 5, shape = 8) +  #Punkt Anwender-Schätzung
    #  scale_color_manual("",values = c("bewässern" = "deepskyblue2",
    #                                   "Schätzung Praxis" = "black") )}
    
    #scale_color_manual("", values = c("Schätzung Praxis" = "black")) + 

ylab("nFK (%)") + xlab("Tage seit Aussaat") +
    theme_bw() +
    theme(panel.grid = element_blank(), legend.position = "right") +
    scale_y_continuous(expand = expansion(add = c(0,10)),
                       breaks = seq(0,100, by = 20)) +
    scale_x_continuous(expand = expansion(add = c(0,0))) +
    scale_x_continuous(expand = expansion(add = c(0,0)),
                       limits = c(range(satz_raw$tage_seit_aussaat))) +
    scale_fill_manual("", values = c("Bewässerungs-\nSchwellenwert" = "grey90",
                                     "Auswaschung" = "lightblue")) +
    geom_vline(xintercept = v_heute, col = "blue") + 
    geom_text(aes(x = v_heute, y = 5, label = v_label),
              col = "blue", vjust=-0.5,hjust = 0,
              angle=90,size=10/.pt) 
#p1

#Punkt Anwender-Schätzung
add_schaetz_punkte <- if(!is.na(any(nfk_anwender$nFK_0010))) {
    list(geom_point(data = nfk_anwender, 
                    aes(tage_seit_aussaat, nFK_0010, 
                        col = "Schätzung Praxis"), size = 5, shape = 8)
    )
} else {
    geom_blank()
}

p_mit_punkt <- p1 + add_schaetz_punkte
```


```{r, fig.width=7*1.2, fig.height=5*1.2, warning=FALSE, fig.cap=cap}
#Beide Plots zusannefügen:
p3 <- plot_grid(p2, p_mit_punkt, labels = c('A', 'B'), label_size = 12, ncol = 1,
                align = "hv", rel_heights = c(1,2.5), axis="t")
p3
```

```{r}
### Grafik speichern
pfad0 <- "../../graphics/ANNI_Praxis/"
feldinfo <- paste(params$betrieb, params$feld, "Satz", params$satz,
                  sep = "_")
zeitraum <- paste0("_DAS", paste0(range(satz_raw$tage_seit_aussaat),
                                  collapse = "_"))
#zeitstempel <- Sys.Date() %>% format("%Y%m%d")
full_name <- paste0(pfad0, paste0(feldinfo, zeitraum, collapse = "_"))

ggsave(p3, filename = paste0(full_name, ".png"), device = "png",
       width = 7, height = 5)

options(width = 80)
foot1 <- (paste0("ANNI Grafik gespeichert unter:\n", file.path(paste0(full_name, ".png"))))
```

```{r}
#Output-Daten speichern:
pfad_csv <- "../../data/derived_data/ANNI_Praxis/"
full_name_csv <- paste0(pfad_csv, paste0(feldinfo, zeitraum, collapse = "_"))
data.table::fwrite(x = result, file = paste0(full_name_csv, ".csv"))

foot2 <- (paste0("ANNI CSV gespeichert unter:\n", file.path(paste0(full_name_csv, ".csv"))))
```

Anmerkung: ANNI wurde in einer Schleife ausgeführt, so dass die modellierte nFK (Output n) als Input (n+1) des folgenden Tages eingeht. [^1] [^2]

[^1]: `r foot1`

[^2]: `r foot2`
