---
title: "3. Tabelle erstellen für einen gewählten Satz Spinat"
author: "Samantha Rubo"
date: '2021-12-10'
output: html_notebook
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggnewscale)
library(tidyr)
```

#Daten-Tabelle erstellen
```{r}
aussaat <- as_date("2021-04-06")
file1 <- "../data/derived_data/nfK_2021_Satz1.csv" #Tensiometer
file2 <- "../data/raw_data/2021_008_Spinat_F6_S1_Klimadaten.csv" #Wetter
file3 <- "../data/derived_data/bewaesserung_mean_2021_S1.csv" #Bewässerung

tensio <- read.csv(file1, sep = ";", dec = ".", row.names = NULL)  %>%
    filter(wasser_level == "Wfull") %>%
    mutate_at("zeit_messung", ~as_date(.,format="%Y-%m-%d")) %>%
    select(zeit_messung, T0020_nFK, T2040_nFK, T4060_nFK)

zeit <- range(tensio$zeit_messung, na.rm = TRUE)

wetter <- read.csv(file2, sep = ";", dec = ",", row.names = NULL) %>%
    mutate_at("Datum", ~as_date(.,format="%Y-%m-%d")) %>%
    filter(Datum %in%  zeit[1]:zeit[2]) %>%
    select("Datum", "Tmax", "Tmin", "Tmean", "RF", "Glob", "P", "RHmin", "V2", "FAO56") %>%
    mutate(Tage_seit_Aussaat = 1) %>%
    mutate_at("Tage_seit_Aussaat", ~cumsum(.) + as.numeric(zeit[1] - aussaat))

bewaesserung <- read.csv(file3, sep = ";", dec = ".", row.names = NULL) %>%
    mutate_at("Datum", ~as_date(.,format="%Y-%m-%d")) %>%
    filter(wasser_level == "Wfull") %>% select(-wasser_level)

#wetter und bewässerung zusammenführen:
input_tabelle <- wetter %>% left_join(bewaesserung, by="Datum") %>%
    left_join(tensio, by=c("Datum" = "zeit_messung")) %>%
    mutate_at("bewaesserung_mm", ~ifelse(is.na(.), 0, .))
```

### Wasserhaltevermögen der Felder der HGU:
|Schicht Nr.|Bezeichnung|100%nFK entsprechen|"Wassergehalt (Vol.% bei 100%nFK)"|
|:---------:|:---------:|:-----------------:|:--------------------------------:|
|   1       |	0-30 cm	|       49.3 mm     |	            16.4%              |
|   2       |  30-60 cm |       46.1 mm     |	            15.4%              |
|   3       |  60-90 cm |       43.4 mm     |               14.5%              |

\
### Vol% Wasser bei 100% nFK für drei Bodentiefen (Schichttiefe je 20cm)
```{r}
T0020_mm_bei100nFK <- 49.3/30*20 #Tabellenwert steht für 30cm Schichtdicke. Umrechnen auf 20cm.
T4060_mm_bei100nFK <- 46.1/30*20
T2040_mm_bei100nFK <- T0020_mm_bei100nFK - (T0020_mm_bei100nFK-T4060_mm_bei100nFK)/2
```
\
### Wassergehalt in mm in der gesamten Bodenschicht 0-60cm anfügen
```{r}
input_tabelle <- input_tabelle %>%
    mutate(T0020_mm = 0.01 * T0020_nFK * T0020_mm_bei100nFK,
           T2040_mm = 0.01 * T2040_nFK * T4060_mm_bei100nFK,
           T4060_mm = 0.01 * T4060_nFK * T2040_mm_bei100nFK) %>%
    mutate(freier_Speicher_T0020_mm = T0020_mm_bei100nFK - T0020_mm,
           freier_Speicher_T2040_mm = T4060_mm_bei100nFK - T2040_mm,
           freier_Speicher_T4060_mm = T2040_mm_bei100nFK - T4060_mm) %>% 
    rowwise() %>%
    mutate(T0060_mm = sum(T0020_mm, T2040_mm, T4060_mm, na.rm = TRUE)) %>%
    ungroup()

input_tabelle
```

\
### Tabelle speichern on Projekt-Ordner für Daten
```{r}
#write.table(x = input_tabelle, file = "../data/derived_data/input_tabelle_2021_Satz1_b.csv", sep = ";",dec = ".", row.names = FALSE)
```


